DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

CONTIKI_PROJECT = example-powerestimation16hz
APPS+=powertrace
all: $(CONTIKI_PROJECT)

CONTIKI = ../../../..
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
